### ISSUE TITLE
[iOS] Setup instructions result in build failure

### ISSUE THREAD

**Issue by skylarmb** [negativetwelve/react-native-amplitude-sdk#6]
Following setup instructions exactly results in this error when trying to build the application

```
Amplitude.m:11:9: fatal error:
      'Amplitude-iOS/Amplitude.h' file not found
#import "Amplitude-iOS/Amplitude.h"
        ^
1 error generated.
```

Header search paths appear to be correct. 

`pod install` installs Amplitude-iOS successfully

```
Downloading dependencies
Installing Amplitude-iOS (3.10.1)
...
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! ...
```

react-native 0.36
xcode 8

**Comment by negativetwelve** [comment]
thanks for reporting @skylarmb, I'll try to take a look later today

**Comment by negativetwelve** [comment]
hi @skylarmb could you provide a screenshot of your xcode tree structure for the Pods project (after running `pod install`)? Make sure to include the Amplitude-iOS pod in the screenshot.

![image](https://cloud.githubusercontent.com/assets/1435378/20381060/8fd1aece-ac5a-11e6-8909-945245de164a.png)

I'm having trouble reproducing the issue on my end. Thanks!

**Comment by skylarmb** [comment]
Hi there @negativetwelve thanks for the quick response. I actually noticed the exact same kind of error (header files not found) happening when trying to integrate a number of other react native libraries and eventually figured out it was because I had `use_frameworks!` in my `Podfile`. I have removed that, `pod install`d, and now and the app compiles just fine. 

Looking forward to the documentation!

**Comment by negativetwelve** [comment]
oh nice! thanks for reporting back!

I haven't had much time to finish the readme but all public methods are exposed via: https://github.com/negativetwelve/react-native-amplitude-sdk/blob/master/src/Amplitude.js which you can start using right now
