### ISSUE TITLE
[iOS] Initial build after setup leads to Xcode error

### ISSUE THREAD

**Issue by vtam311** [negativetwelve/react-native-amplitude-sdk#9]
Thanks for building a great package.

After performing the setup instructions, and getting a successful pod install, I get the Xcode error:
'RCTBridgeModule.h' file not found from RNAmplitude.h.

I'm using RN 0.39.2, and Xcode 8.2.1. Any idea what the issue is?

**Comment by negativetwelve** [comment]
Can you try using the 0.2.0 version (https://github.com/negativetwelve/react-native-amplitude-sdk/releases/tag/0.2.0)? That should work with 0.39.2, there was a breaking change released for 0.40.0 - I should add this to the readme!

**Comment by negativetwelve** [comment]
`yarn add react-native-amplitude-sdk@0.2.0` should work!

**Comment by vtam311** [comment]
Thanks for the quick response. I tried using 0.2.0 and unfortunately I'm getting the same error. Still probing around to find out what it could be.

**Comment by vtam311** [comment]
Just want to update you that I've fixed the issue. 

If anyone runs into the same bug, I was able to fix it by going to the react-native-amplitude-sdk target, build settings, header search paths, and then inputting in:

$(SRCROOT)/../../node_modules/react-native/React
$(SRCROOT)/../../node_modules/react-native/Libraries

**Comment by negativetwelve** [comment]
oh nice! Do you want to submit a pull request to add those to the header search paths?

**Comment by vtam311** [comment]
I made the changes off of version 0.2.0, and also forgot to mention that I
changed the podspec file to not include React as a dependency, since that
was leading to issues as well.

I can try updating the version, and see if it still works. If so, I can
make a PR. Otherwise it may be a bit too messy :)

**Comment by negativetwelve** [comment]
ahh gotcha, I believe master has the React dependency removed as well. We're going to update our app to past 0.40+ in the next week or so, so I'll update this library (and include your header search paths) when we get to that point. 

Thanks again for helping track down that issue, I hope this issue is useful for others!
